### GET Produto
GET http://localhost:5262/produtos

### GET Produto por id
GET http://localhost:5262/produto/1

### GET Produto Disponíveis
GET http://localhost:5262/produtos/disponiveis

### POST Produto
POST http://localhost:5262/produto
Content-Type: application/json

{
  "Nome": "abc",
  "Descricao": "def",
  "Quantidade": 10,
  "Valor": 27.50,
  "Tag": "Eletronico"
}

### PUT Produto
PUT http://localhost:5262/produto/1
Content-Type: application/json

{
  "Nome": "xyz",
  "Descricao": "def",
  "Quantidade": 2,
  "Valor": 27.50,
  "Tag": "Eletronico"
}

### DELETE Produto
DELETE http://localhost:5262/produto/1

### GET /cupom
GET http://localhost:5262/cupom

### GET /cupom/{id}
GET http://localhost:5262/cupom/1

### POST /cupom
POST http://localhost:5262/cupom
Content-Type: application/json

{
  "codigo": "5%OFF",
  "desconto": 0.005,
  "usado": false,
  "valormin": 550.0
}


### PUT /cupom
PUT http://localhost:5262/cupom/2
Content-Type: application/json

{
  "codigo": "10%OFF",
  "desconto": 0.010,
  "usado": false,
  "valormin": 550.0
}

### DELETE /cupom/{id}
DELETE http://localhost:5262/cupom/1
