### GET /clientes
GET http://localhost:5262/clientes

### GET /clientes/{id}
GET http://localhost:5262/clientes/1

### POST /clientes
POST http://localhost:5262/clientes
Content-Type: application/json

{
    "Nome": "Junior",
    "Email": "junior@email.com",
    "Senha": "juniorBrabinho",
    "IdCarrinho": 1,
    "IdComprasHist": 1
}

### PUT /clientes/{id}
PUT http://localhost:5262/clientes/1
Content-Type: application/json

{
    "Nome": "Juninho Bala",
    "Email": "junior@email.com",
    "Senha": "juniorBrabinho",
    "IdCarrinho": 1,
    "IdComprasHist": 1
}

### DELETE /clientes/{id}
DELETE http://localhost:5262/clientes/4


### GET /vendedores
GET http://localhost:5262/vendedores

### GET /vendedores/{id}
GET http://localhost:5262/vendedores/10

### POST /vendedores
POST http://localhost:5262/vendedores
Content-Type: application/json

{
    "Nome": "Thiago",
    "Email": "thiago@email.com",
    "Senha": "thiagoTenebroso",
    "IdVenda": 1,
    "IdVendaHist": 1
}

### PUT /vendedores/{id}
PUT http://localhost:5262/vendedores/8
Content-Type: application/json

{
    "Nome": "Thiago Bento",
    "Email": "thiago@email.com",
    "Senha": "thiagoTenebroso",
    "IdVenda": 1,
    "IdVendaHist": 1
}

### DELETE /vendedores/{id}
DELETE http://localhost:5262/vendedores/8



### GET /administradores
GET http://localhost:5262/administradores

### GET /administradores/{id}
GET http://localhost:5262/administradores/1

### POST /administradores
POST http://localhost:5262/administradores
Content-Type: application/json

{
    "Nome": "Benedito",
    "Email": "benedito@email.com",
    "Senha": "beneditoOVelho",
    "PinAcesso": 1243
}

### PUT /administradores/{id}
PUT http://localhost:5262/administradores/1
Content-Type: application/json

{
    "Nome": "Benedito Santiago",
    "Email": "benedito@email.com",
    "Senha": "beneditoOTecnico",
    "PinAcesso": 1243
}

### DELETE /administradores/{id}
DELETE http://localhost:5262/administradores/4

### GET Produto
GET http://localhost:5262/produtos

### GET Produto por id
GET http://localhost:5262/produtos/22

### GET Produto Disponíveis
GET http://localhost:5262/produtos/disponiveis

### POST Produto
POST http://localhost:5262/produtos
Content-Type: application/json

{
  "Nome": "compuator",
  "Descricao": "caomptuador gamer",
  "Quantidade": 2,
  "Valor": 2000,
  "Tag": "Eletronico"
}

### PUT Produto
PUT http://localhost:5262/produtos/22
Content-Type: application/json

{
  "Nome": "xyz",
  "Descricao": "def",
  "Quantidade": 2,
  "Valor": 27.50,
  "Tag": "Eletronico"
}

### DELETE Produto
DELETE http://localhost:5262/produtos/2

### GET /cupom
GET http://localhost:5262/cupons

### GET /cupom/{id}
GET http://localhost:5262/cupons/1

### POST /cupom
POST http://localhost:5262/cupons
Content-Type: application/json

{
  "codigo": "5%OFF",
  "desconto": 0.005,
  "usado": false,
  "valormin": 550.0
}


### PUT /cupom
PUT http://localhost:5262/cupons/2
Content-Type: application/json

{
  "codigo": "10%OFF",
  "desconto": 0.010,
  "usado": false,
  "valormin": 550.0
}

### DELETE /cupom/{id}
DELETE http://localhost:5262/cupons/1

###GET /vendas
GET http://localhost:5262/vendas

###GET /vendas/cliente/{idCliente}
GET http://localhost:5262/vendas/cliente/1

###GET /vendas/{id}
GET http://localhost:5262/vendas/1

### POST /vendas
POST http://localhost:5262/vendas
Content-Type: application/json

{
  "IdCliente": 1,
  "Itens": [
    {
      "ProdutoId": 1,
      "Quantidade": 19
    },
    {
      "ProdutoId": 2,
      "Quantidade": 22
    }
  ]
}



### PUT /vendas
PUT http://localhost:5262/vendas/1
Content-Type: application/json

{
  "IdCliente": 12301
}

### DELETE /vendas/{id}
DELETE http://localhost:5262/vendas/2

### ENDEREÇOS

### GET /enderecos
GET http://localhost:5262/enderecos

### GET /enderecos/{id}
GET http://localhost:5262/enderecos/2

### POST /enderecos
POST http://localhost:5262/enderecos
Content-Type: application/json

{
  "IdCliente": 101,
  "Rua": "Rua das Flores",
  "numero": 123,
  "bairro": "Centro",
  "cidade": "São Paulo",
  "estado": "SP",
  "cep": "01001-000",
  "complemento": "Apto 201"
}

### PUT /enderecos/{id}
PUT http://localhost:5262/enderecos/2
Content-Type: application/json

{
  "IdCliente": 101,
    "Rua": "Avenida Paulista",
  "numero": 456,
  "bairro": "Bela Vista",
  "cidade": "São Paulo",
  "estado": "SP",
  "cep": "01311-000",
  "complemento": "Sala 101"
}

### DELETE /enderecos/{id}
DELETE http://localhost:5262/enderecos/2

### CARRINHO

### GET /carrinho
GET http://localhost:5262/carrinho

### GET /carrinho/{id}
GET http://localhost:5262/carrinho/7

### POST /carrinho
POST http://localhost:5262/carrinho
Content-Type: application/json

{
  "usuarioId": 1,
  "itens": [
    {
      "produtoId": 5,
      "quantidade": 2
    },
    {
      "produtoId": 3,
      "quantidade": 1
    }
  ]
}


### PUT /carrinho/{id}
PUT http://localhost:5262/carrinho/7
Content-Type: application/json

{
  "usuarioId": 3,
  "itens": [
    {
      "produtoId": 2,
      "quantidade": 6
    },
    {
      "produtoId": 1,
      "quantidade": 3
    }
  ]
}

### DELETE /carrinho/{id}
DELETE http://localhost:5262/carrinho/9