### POST Produto
POST http://localhost:5262/produtos
Content-Type: application/json

 {
      "nome": "Notebook",
      "descricao": "Notebook com 16GB RAM e 512GB SSD",
      "quantidade": 2,
      "valor": 3500.00,
      "tag": "eletronico"
}

### POST Produto
POST http://localhost:5262/produtos
Content-Type: application/json

    {
      "nome": "Mouse Gamer",
      "descricao": "Mouse com iluminação RGB e sensor de alta precisão",
      "quantidade": 1,
      "valor": 150.00,
      "tag": "acessorio"
    }

### POST /vendas
POST http://localhost:5262/vendas
Content-Type: application/json

{
  "IdCliente": 101,
  "Itens": [
    {
      "ProdutoId": 122,
      "Quantidade": 12
    },
    {
      "ProdutoId": 223,
      "Quantidade": 21
    }
  ]
}

### POST /vendas
POST http://localhost:5262/vendas
Content-Type: application/json

{
  "IdCliente": 1111,
  "Itens": [
    {
      "ProdutoId": 12,
      "Quantidade": 1
    },
    {
      "ProdutoId": 22,
      "Quantidade": 2
    }
  ]
}