### GET
GET http://localhost:5262/produtos

### GET por id
GET http://localhost:5262/produto/1

### GET Disponíveis
GET http://localhost:5262/produtos/disponiveis

### POST
POST http://localhost:5262/produto
Content-Type: application/json

{
  "Nome": "abc",
  "Descricao": "def",
  "Quantidade": 10,
  "Valor": 27.50,
  "Tag": "Eletronico"
}

### PUT
PUT http://localhost:5262/produto/1
Content-Type: application/json

{
  "Nome": "xyz",
  "Descricao": "def",
  "Quantidade": 2,
  "Valor": 27.50,
  "Tag": "Eletronico"
}

### DELETE
DELETE http://localhost:5262/produto/1